# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter
from lob.models.sort_by_1 import SortBy1
from lob.models.self_mailer_editable import SelfMailerEditable


class SelfMailersControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(SelfMailersControllerTests, cls).setUpClass()
        cls.controller = cls.client.self_mailers
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your self_mailers. The self_mailers are returned sorted by creation date, with the most recently created self_mailers appearing first.
    def test_self_mailers_list(self):
        # Parameters for the API call
        limit = 10
        before_after = None
        include = None
        date_created = None
        metadata = None
        size = None
        scheduled = None
        send_date = None
        mail_type = None
        sort_by = None

        # Perform the API call through the SDK function
        result = self.controller.self_mailers_list(limit, before_after, include, date_created, metadata, size, scheduled, send_date, mail_type, sort_by)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"sfm_7239rhwqkrfaskas","description":"April Campaig'
            'n","metadata":{},"to":{"id":"adr_asdi2y3riuasasoi","description":"'
            'Harry - Office","name":"Harry Zhang","company":"Lob","phone":"5555'
            '555555","email":"harry@lob.com","metadata":{},"address_line1":"370'
            ' WATER ST","address_line2":"","address_city":"SUMMERSIDE","address'
            '_state":"PRINCE EDWARD ISLAND","address_zip":"C1N 1C4","address_co'
            'untry":"CANADA","recipient_moved":false,"date_created":"2019-09-20'
            'T00:14:00.361Z","date_modified":"2019-09-20T00:14:00.361Z","object'
            '":"address"},"from":{"id":"adr_210a8d4b0b76d77b","description":nul'
            'l,"name":null,"company":"LOB","phone":null,"email":null,"address_l'
            'ine1":"210 KING ST STE 6100","address_line2":null,"address_city":"'
            'SAN FRANCISCO","address_state":"CA","address_zip":"94107-1741","ad'
            'dress_country":"UNITED STATES","metadata":{},"date_created":"2018-'
            '12-08T03:01:07.651Z","date_modified":"2018-12-08T03:01:07.651Z","o'
            'bject":"address"},"url":"https://lob-assets.com/self-mailers/sfm_8'
            'ffbe811dea49dcf.pdf?version=v1&expires=1618781264&signature=YP_bCw'
            'rgVA2lz1Gr1YVCJN1f-WspUGsH0aJp2ihjfLXU7lDUV12_xRv4uPch0mfWeOOxEqpy'
            'P8hGpgvjmQKNAw","outside_template_id":"tmpl_a3cb937f26d7eec","insi'
            'de_template_id":"tmpl_a3cb937f26d7eec","inside_template_version_id'
            '":"vrsn_bfdf70893b00a85","outside_template_version_id":"vrsn_bfdf7'
            '0893b00a85","carrier":"USPS","tracking_events":[],"thumbnails":[{"'
            'small":"https://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf_t'
            'humb_small_1.png?version=v1&expires=1618781264&signature=A7q5HbRO5'
            '3sUYYnwGlmP5mTS6ylLE7kS2mYhfcEOdexjyqG7UseK0MD26DppE4Q0aE4u2msDVMx'
            'd5ukjMerYCg","medium":"https://lob-assets.com/self-mailers/sfm_8ff'
            'be811dea49dcf_thumb_medium_1.png?version=v1&expires=1618781264&sig'
            'nature=b9pynuawVpU_vrhnT_mTpksdE-FLF_ZjdIBOFR_ltIzEGlx-VKD4VvZrqP9'
            '8lG2D8V7UKQ7SdRr2nUAk4LxvCg","large":"https://lob-assets.com/self-'
            'mailers/sfm_8ffbe811dea49dcf_thumb_large_1.png?version=v1&expires='
            '1618781264&signature=g2jifhCselPqIj8au6lsbJMNFN8ZX3aM6GkLoAXiHBCS8'
            'X5mF9nhVbmO0odpnmwNlV1CWIp-MXVsZkC3NmxqBQ"},{"small":"https://lob-'
            'assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_small_2.png?ver'
            'sion=v1&expires=1618781264&signature=biJY4-ZbNNRydPYg3cZkq7wxjILbP'
            'BK_nIVyoyQsg5X5q4jlsa-2fzeMa48V9jprUetsC6WEuYvasHosRfG_DQ","medium'
            '":"https://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_'
            'medium_2.png?version=v1&expires=1618781264&signature=xEAX7bURyc8fS'
            'phacuo5yb7iVIpT8Xvq05KgMaNQS4r3aCpx0z1p42wbPmW758B5Ae0li1YDYvVyzS7'
            'qJIoWAw","large":"https://lob-assets.com/self-mailers/sfm_8ffbe811'
            'dea49dcf_thumb_large_2.png?version=v1&expires=1618781264&signature'
            '=NieHDnoQ7STZUvofHrFt7S987CzIkUJWpaSgpVQPZw-C3_wwTPsIrvxYdXEuFrr6c'
            'iTUcxRBFPlE0lurmMkyCA"}],"merge_variables":{"name":null},"size":"6'
            'x18_bifold","mail_type":"usps_first_class","expected_delivery_date'
            '":"2021-03-24","date_created":"2021-03-16T18:40:40.504Z","date_mod'
            'ified":"2021-03-16T18:41:06.691Z","send_date":"2021-03-16T18:45:40'
            '.493Z","deleted":true,"use_type":"marketing","fsc":false,"object":'
            '"self_mailer"},{"id":"sfm_8ffbe811dea49dcf","description":"April C'
            'ampaign","metadata":{},"to":{"id":"adr_f9228b743884ff98","descript'
            'ion":null,"name":"AYA","company":null,"phone":null,"email":null,"a'
            'ddress_line1":"2812 PARK RD","address_line2":null,"address_city":"'
            'CHARLOTTE","address_state":"NC","address_zip":"28209-1314","addres'
            's_country":"UNITED STATES","metadata":{},"date_created":"2021-03-1'
            '6T18:40:40.410Z","date_modified":"2021-03-16T18:40:40.410Z","delet'
            'ed":true,"object":"address"},"from":{"id":"adr_210a8d4b0b76d77b","'
            'description":null,"name":null,"company":"LOB","phone":null,"email"'
            ':null,"address_line1":"210 KING ST STE 6100","address_line2":null,'
            '"address_city":"SAN FRANCISCO","address_state":"CA","address_zip":'
            '"94107-1741","address_country":"UNITED STATES","metadata":{},"date'
            '_created":"2018-12-08T03:01:07.651Z","date_modified":"2018-12-08T0'
            '3:01:07.651Z","object":"address"},"url":"https://lob-assets.com/se'
            'lf-mailers/sfm_8ffbe811dea49dcf.pdf?version=v1&expires=1618781264&'
            'signature=YP_bCwrgVA2lz1Gr1YVCJN1f-WspUGsH0aJp2ihjfLXU7lDUV12_xRv4'
            'uPch0mfWeOOxEqpyP8hGpgvjmQKNAw","outside_template_id":"tmpl_a3cb93'
            '7f26d7eec","inside_template_id":"tmpl_a3cb937f26d7eec","inside_tem'
            'plate_version_id":"vrsn_bfdf70893b00a85","outside_template_version'
            '_id":"vrsn_bfdf70893b00a85","carrier":"USPS","tracking_events":[],'
            '"thumbnails":[{"small":"https://lob-assets.com/self-mailers/sfm_8f'
            'fbe811dea49dcf_thumb_small_1.png?version=v1&expires=1618781264&sig'
            'nature=A7q5HbRO53sUYYnwGlmP5mTS6ylLE7kS2mYhfcEOdexjyqG7UseK0MD26Dp'
            'pE4Q0aE4u2msDVMxd5ukjMerYCg","medium":"https://lob-assets.com/self'
            '-mailers/sfm_8ffbe811dea49dcf_thumb_medium_1.png?version=v1&expire'
            's=1618781264&signature=b9pynuawVpU_vrhnT_mTpksdE-FLF_ZjdIBOFR_ltIz'
            'EGlx-VKD4VvZrqP98lG2D8V7UKQ7SdRr2nUAk4LxvCg","large":"https://lob-'
            'assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_large_1.png?ver'
            'sion=v1&expires=1618781264&signature=g2jifhCselPqIj8au6lsbJMNFN8ZX'
            '3aM6GkLoAXiHBCS8X5mF9nhVbmO0odpnmwNlV1CWIp-MXVsZkC3NmxqBQ"},{"smal'
            'l":"https://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb'
            '_small_2.png?version=v1&expires=1618781264&signature=biJY4-ZbNNRyd'
            'PYg3cZkq7wxjILbPBK_nIVyoyQsg5X5q4jlsa-2fzeMa48V9jprUetsC6WEuYvasHo'
            'sRfG_DQ","medium":"https://lob-assets.com/self-mailers/sfm_8ffbe81'
            '1dea49dcf_thumb_medium_2.png?version=v1&expires=1618781264&signatu'
            're=xEAX7bURyc8fSphacuo5yb7iVIpT8Xvq05KgMaNQS4r3aCpx0z1p42wbPmW758B'
            '5Ae0li1YDYvVyzS7qJIoWAw","large":"https://lob-assets.com/self-mail'
            'ers/sfm_8ffbe811dea49dcf_thumb_large_2.png?version=v1&expires=1618'
            '781264&signature=NieHDnoQ7STZUvofHrFt7S987CzIkUJWpaSgpVQPZw-C3_wwT'
            'PsIrvxYdXEuFrr6ciTUcxRBFPlE0lurmMkyCA"}],"merge_variables":{"name"'
            ':null},"size":"6x18_bifold","mail_type":"usps_first_class","expect'
            'ed_delivery_date":"2021-03-24","date_created":"2021-03-16T18:40:40'
            '.504Z","date_modified":"2021-03-16T18:41:06.691Z","send_date":"202'
            '1-03-16T18:45:40.493Z","deleted":true,"use_type":"marketing","fsc"'
            ':true,"object":"self_mailer"}],"object":"list","next_url":null,"pr'
            'evious_url":null,"count":2}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Creates a new self_mailer given information
    def test_self_mailer_create(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"description":"Demo Self Mailer job","to":"adr_bae820679f3f536b",'
            '"from":"adr_210a8d4b0b76d77b","inside":"https://lob.com/selfmailer'
            'inside.pdf","outside":"https://lob.com/selfmaileroutside.pdf","siz'
            'e":"12x9_bifold","metadata":{"spiffy":"true"},"mail_type":"usps_st'
            'andard","merge_variables":{"name":"Harry"},"send_date":"2017-11-01'
            'T00:00:00.000Z","use_type":"marketing","qr_code":{"position":"rela'
            'tive","redirect_url":"https://www.lob.com","width":"2.5","top":"2.'
            '5","right":"2.5","pages":"inside,outside"},"fsc":true}', SelfMailerEditable.from_dictionary)
        idempotency_key = '026e7634-24d7-486c-a0bb-4a17fd0eebc5'
        idempotency_key_2 = '026e7634-24d7-486c-a0bb-4a17fd0eebc5'

        # Perform the API call through the SDK function
        result = self.controller.self_mailer_create(body, idempotency_key, idempotency_key_2)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":"sfm_8ffbe811dea49dcf","description":"April Campaign","metad'
            'ata":{},"to":{"id":"adr_bae820679f3f536b","description":null,"name'
            '":"HARRY ZHANG","company":null,"phone":null,"email":null,"address_'
            'line1":"210 KING ST STE 6100","address_line2":null,"address_city":'
            '"SAN FRANCISCO","address_state":"CA","address_zip":"94107-1741","a'
            'ddress_country":"UNITED STATES","metadata":{},"date_created":"2017'
            '-09-05T17:47:53.767Z","date_modified":"2017-09-05T17:47:53.767Z","'
            'deleted":true,"object":"address"},"from":{"id":"adr_210a8d4b0b76d7'
            '7b","description":null,"name":"LEORE AVIDAR","company":null,"phone'
            '":null,"email":null,"address_line1":"210 KING ST STE 6100","addres'
            's_line2":null,"address_city":"SAN FRANCISCO","address_state":"CA",'
            '"address_zip":"94107-1741","address_country":"UNITED STATES","meta'
            'data":{},"date_created":"2017-09-05T17:47:53.767Z","date_modified"'
            ':"2017-09-05T17:47:53.767Z","deleted":true,"object":"address"},"ur'
            'l":"https://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf.pdf?v'
            'ersion=v1&expires=1618512040&signature=qvyCqXI1ndBvc4AjvG8FlirqLXE'
            'cfmYo4sDrRtabaXMOsX88to9G3K49uIk_aqevvZXe8HoRYD_nWydbQHqaCA","outs'
            'ide_template_id":"tmpl_a3cb937f26d7eec","inside_template_id":"tmpl'
            '_a3cb937f26d7eec","inside_template_version_id":"vrsn_bfdf70893b00a'
            '85","outside_template_version_id":"vrsn_bfdf70893b00a85","carrier"'
            ':"USPS","tracking_events":[],"thumbnails":[{"small":"https://lob-a'
            'ssets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_small_1.png?vers'
            'ion=v1&expires=1618512040&signature=-bipeUHP-hAMcCBSrWM0ZH1VwRdSPN'
            'VGGZN9hAZKr6Lh4ly6uxvratVd5LXJCK_zOEMYk_mTWASt0ge7OY6SDA","medium"'
            ':"https://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_m'
            'edium_1.png?version=v1&expires=1618512040&signature=ryxN7bsXGtw_GR'
            'FSP3Cs3A3IYjxZi3cW9BHDCNgMt6p3nobVmsc_iFHt2e-S7ndAXhhN7nP-MQVov3bt'
            '3r37BQ","large":"https://lob-assets.com/self-mailers/sfm_8ffbe811d'
            'ea49dcf_thumb_large_1.png?version=v1&expires=1618512040&signature='
            'kBrm00xkyCkJNJRHxH8HshFaebtOxnzjVWOs1VVmGMuw8H6OBNcMAMxt9s49K0jlpH'
            'oh3Nr9uSncEZMQaaNjAg"},{"small":"https://lob-assets.com/self-maile'
            'rs/sfm_8ffbe811dea49dcf_thumb_small_2.png?version=v1&expires=16185'
            '12040&signature=3gTgU7Fd3KoT_vNlQnTGptRps5ZgnkhSnPrAwk7L98higIzSwf'
            'KoLvuu_DIpMM48dHbxckKT9waR8euJ4KSDBQ","medium":"https://lob-assets'
            '.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_medium_2.png?version='
            'v1&expires=1618512040&signature=Ue1lw5CMj7KRx6cMQL8xPeazaHCdJzWcAC'
            'd1w3acuYPnWkVIpSt62OIO7hAtpAQK9xm1dhhlFj0rqRZMdRMMBA","large":"htt'
            'ps://lob-assets.com/self-mailers/sfm_8ffbe811dea49dcf_thumb_large_'
            '2.png?version=v1&expires=1618512040&signature=cICc7HEm1xG_eyM4a_wt'
            'vPk2FqoLRmtgGa29kJisWnMIYBL0OkyzG4ZCYGMhp-5cZpJlSpXfTgGKh_Qmeo1TDw'
            '"}],"merge_variables":{"name":null},"size":"6x18_bifold","mail_typ'
            'e":"usps_first_class","expected_delivery_date":"2021-03-24","date_'
            'created":"2021-03-16T18:40:40.504Z","date_modified":"2021-03-16T18'
            ':40:40.504Z","send_date":"2021-03-16T18:45:40.493Z","use_type":"ma'
            'rketing","fsc":false,"object":"self_mailer"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

