# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper


class IdentityValidationControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(IdentityValidationControllerTests, cls).setUpClass()
        cls.controller = cls.client.identity_validation
        cls.response_catcher = cls.controller.http_call_back

    # Validates whether a given name is associated with an address.
    def test_identity_validation(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"recipient":"Larry Lobster","primary_line":"210 King St.","second'
            'ary_line":"","city":"San Francisco","state":"CA","zip_code":"94107'
            '"}')

        # Perform the API call through the SDK function
        result = self.controller.identity_validation(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


