# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter


class BankAccountsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(BankAccountsControllerTests, cls).setUpClass()
        cls.controller = cls.client.bank_accounts
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your bank accounts. The bank accounts are returned sorted by creation date, with the most recently created bank accounts appearing first.
    def test_bank_accounts_list(self):
        # Parameters for the API call
        limit = 10
        before_after = None
        include = None
        date_created = None
        metadata = None

        # Perform the API call through the SDK function
        result = self.controller.bank_accounts_list(limit, before_after, include, date_created, metadata)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"bank_0e3fb07eba0b35b","signature_url":"https://lob'
            '-assets.com/letters/asd_asdfghjklqwertyu.pdf?version=45&expires=12'
            '34567890&signature=a","description":"Example bank account","metada'
            'ta":{},"routing_number":"122100024","account_number":"1234564789",'
            '"account_type":"company","signatory":"John Doe","bank_name":"JPMOR'
            'GAN CHASE BANK, NA","verified":true,"date_created":"2019-03-30T13:'
            '13:22.200Z","date_modified":"2019-03-30T13:13:23.385Z","object":"b'
            'ank_account"},{"id":"bank_eba93f7de3c02d9","description":"Example '
            'bank account","metadata":{},"routing_number":"122100024","account_'
            'number":"1234564789","account_type":"company","signatory":"John Do'
            'e","bank_name":"JPMORGAN CHASE BANK, NA","verified":true,"date_cre'
            'ated":"2019-03-30T13:11:06.809Z","date_modified":"2019-03-30T13:11'
            ':07.872Z","object":"bank_account"}],"object":"list","next_url":"ht'
            'tps://api.lob.com/v1/bank_accounts?limit=2&after=eyJkYXRlT2Zmc2V0I'
            'joiMjAxOS0wMy0zMFQxMzoxMTowNi44MDlaIiwiaWRPZmZzZXQiOiJiYW5rX2ViYTk'
            'zZjdkZTNjMDJkOSJ9","previous_url":null,"count":2}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

