# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper


class URLShortenerControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(URLShortenerControllerTests, cls).setUpClass()
        cls.controller = cls.client.url_shortener
        cls.response_catcher = cls.controller.http_call_back

    # Retrieve a list of all created domains.
    def test_domain_list(self):

        # Perform the API call through the SDK function
        result = self.controller.domain_list()

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


    # Retrieves a list of shortened links. The list is sorted by  creation date, with the most recently created appearing first.
    def test_links_list(self):
        # Parameters for the API call
        limit = 10
        offset = 0
        include = None
        date_created = None
        metadata = None
        campaign_id = None
        clicked = None
        billing_group_id = None

        # Perform the API call through the SDK function
        result = self.controller.links_list(limit, offset, include, date_created, metadata, campaign_id, clicked, billing_group_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


