# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json
import dateutil.parser

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter


class CampaignsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(CampaignsControllerTests, cls).setUpClass()
        cls.controller = cls.client.campaigns
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your campaigns. The campaigns are returned sorted by creation date, with the most recently created campaigns appearing first.
    def test_campaigns_list(self):
        # Parameters for the API call
        limit = 10
        include = None
        before_after = None

        # Perform the API call through the SDK function
        result = self.controller.campaigns_list(limit, include, before_after)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"cmp_e05ee61ff80764b","billing_group_id":"bg_fe3079'
            'dcdd80e5ae","name":"My Campaign","description":"My Campaign\'s des'
            'cription","schedule_type":"immediate","send_date":null,"target_del'
            'ivery_date":null,"cancel_window_campaign_minutes":60,"metadata":{}'
            ',"use_type":"marketing","is_draft":true,"deleted":false,"creatives'
            '":[],"uploads":[],"auto_cancel_if_ncoa":false,"date_created":"2017'
            '-09-05T17:47:53.767Z","date_modified":"2017-09-05T17:47:53.767Z","'
            'object":"campaign"}],"object":"list","previous_url":null,"next_url'
            '":null,"count":1}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

