# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper


class CreativesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(CreativesControllerTests, cls).setUpClass()
        cls.controller = cls.client.creatives
        cls.response_catcher = cls.controller.http_call_back

    # Retrieves the details of an existing creative. You need only supply the unique creative identifier that was returned upon creative creation.
    def test_creative_retrieve(self):
        # Parameters for the API call
        crv_id = 'crv_2a3b096c409b32c'

        # Perform the API call through the SDK function
        result = self.controller.creative_retrieve(crv_id)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


