# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter


class AddressesControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(AddressesControllerTests, cls).setUpClass()
        cls.controller = cls.client.addresses
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your addresses. The addresses are returned sorted by creation date, with the most recently created addresses appearing first.
    def test_addresses_list(self):
        # Parameters for the API call
        limit = 10
        before_after = None
        include = None
        date_created = None
        metadata = None

        # Perform the API call through the SDK function
        result = self.controller.addresses_list(limit, before_after, include, date_created, metadata)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"adr_e68217bd744d65c8","description":"Harry - Offic'
            'e","name":"HARRY ZHANG","company":"LOB","phone":"5555555555","emai'
            'l":"harry@lob.com","address_line1":"210 KING ST STE 6100","address'
            '_line2":null,"address_city":"SAN FRANCISCO","address_state":"CA","'
            'address_zip":"94107-1741","address_country":"UNITED STATES","metad'
            'ata":{},"date_created":"2019-08-12T00:16:00.361Z","date_modified":'
            '"2019-08-12T00:16:00.361Z","object":"address"},{"id":"adr_asdi2y3r'
            'iuasasoi","description":"Harry - Office","name":"Harry Zhang","com'
            'pany":"Lob","phone":"5555555555","email":"harry@lob.com","metadata'
            '":{},"address_line1":"370 WATER ST","address_line2":"","address_ci'
            'ty":"SUMMERSIDE","address_state":"PRINCE EDWARD ISLAND","address_z'
            'ip":"C1N 1C4","address_country":"CANADA","date_created":"2019-09-2'
            '0T00:14:00.361Z","date_modified":"2019-09-20T00:14:00.361Z","objec'
            't":"address"}],"object":"list","next_url":"https://api.lob.com/v1/'
            'addresses?limit=2&after=eyJkYXRlT2Zmc2V0IjoiMjAxOS0wOC0wN1QyMTo1OT'
            'o0Ni43NjRaIiwiaWRPZmZzZXQiOiJhZHJfODMwYmYwZWFiZGFhYTQwOSJ9","previ'
            'ous_url":null,"count":2}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Creates a new address given information
    def test_address_create(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"description":"Harry - Office","name":"Harry Zhang","company":"Lo'
            'b","email":"harry@lob.com","phone":"5555555555","address_line1":"2'
            '10 King St","address_line2":"# 6100","address_city":"San Francisco'
            '","address_state":"CA","address_zip":"94107","address_country":"US'
            '"}')

        # Perform the API call through the SDK function
        result = self.controller.address_create(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":"adr_d3489cd64c791ab5","description":"Harry - Office","name"'
            ':"HARRY ZHANG","company":"LOB","phone":"5555555555","email":"harry'
            '@lob.com","address_line1":"210 KING ST STE 6100","address_city":"S'
            'AN FRANCISCO","address_state":"CA","address_zip":"94107","address_'
            'country":"UNITED STATES","metadata":{},"date_created":"2017-09-05T'
            '17:47:53.767Z","date_modified":"2017-09-05T17:47:53.767Z","object"'
            ':"address"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

