# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter
from lob.models.sort_by_1 import SortBy1
from lob.models.postcard_editable import PostcardEditable


class PostcardsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(PostcardsControllerTests, cls).setUpClass()
        cls.controller = cls.client.postcards
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your postcards. The addresses are returned sorted by creation date, with the most recently created addresses appearing first.
    def test_postcards_list(self):
        # Parameters for the API call
        limit = 10
        before_after = None
        include = None
        date_created = None
        metadata = None
        size = None
        scheduled = None
        send_date = None
        mail_type = None
        sort_by = None

        # Perform the API call through the SDK function
        result = self.controller.postcards_list(limit, before_after, include, date_created, metadata, size, scheduled, send_date, mail_type, sort_by)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"psc_208e45e48d271294","description":null,"metadata'
            '":{},"to":{"id":"adr_210a8d4b0b76d77b","description":null,"name":"'
            'LEORE AVIDAR","company":null,"phone":null,"email":null,"address_li'
            'ne1":"210 KING ST STE 6100","address_line2":null,"address_city":"S'
            'AN FRANCISCO","address_state":"CA","address_zip":"94107-1741","add'
            'ress_country":"UNITED STATES","metadata":{},"date_created":"2018-1'
            '2-08T03:01:07.651Z","date_modified":"2018-12-08T03:01:07.651Z","ob'
            'ject":"address"},"url":"https://lob-assets.com/postcards/psc_208e4'
            '5e48d271294.pdf?version=v1&expires=1619218302&signature=NfHHLBSr5t'
            'OHA_Z4kij4dKqZG8f3vMDtwvuFVeeF9pV_lylcjLsVVODhNCE5hR6-2slUr6t9WMNs'
            'i429Pj7_DA","carrier":"USPS","front_template_id":null,"back_templa'
            'te_id":null,"front_template_version_id":null,"back_template_versio'
            'n_id":null,"date_created":"2021-03-24T22:51:42.838Z","date_modifie'
            'd":"2021-03-24T22:51:42.838Z","send_date":"2021-03-24T22:51:42.838'
            'Z","use_type":"marketing","object":"postcard"},{"id":"psc_0e03d1ad'
            '7d31f151","description":null,"metadata":{},"to":{"id":"adr_c7cb63d'
            '68f8d6","description":null,"name":"JANE DOE","company":"LOB","phon'
            'e":"5555555555","email":"jane.doe@lob.com","address_line1":"370 WA'
            'TER ST","address_line2":"","address_city":"SUMMERSIDE","address_st'
            'ate":"PE","address_zip":"C1N 1C4","address_country":"CANADA","meta'
            'data":{},"date_created":"2018-12-08T03:01:07.651Z","date_modified"'
            ':"2018-12-08T03:01:07.651Z","object":"address","recipient_moved":f'
            'alse},"from":{"id":"adr_210a8d4b0b76d77b","description":null,"name'
            '":"LEORE AVIDAR","company":null,"phone":null,"email":null,"address'
            '_line1":"210 KING ST STE 6100","address_line2":null,"address_city"'
            ':"SAN FRANCISCO","address_state":"CA","address_zip":"94107-1741","'
            'address_country":"UNITED STATES","metadata":{},"date_created":"201'
            '8-12-08T03:01:07.651Z","date_modified":"2018-12-08T03:01:07.651Z",'
            '"object":"address"},"url":"https://lob-assets.com/postcards/psc_20'
            '8e45e48d271294.pdf?version=v1&expires=1619218302&signature=NfHHLBS'
            'r5tOHA_Z4kij4dKqZG8f3vMDtwvuFVeeF9pV_lylcjLsVVODhNCE5hR6-2slUr6t9W'
            'MNsi429Pj7_DA","carrier":"USPS","front_template_id":null,"back_tem'
            'plate_id":null,"front_template_version_id":null,"back_template_ver'
            'sion_id":null,"tracking_events":[],"size":"6x11","mail_type":"usps'
            '_first_class","merge_variables":{},"thumbnails":[{"small":"https:/'
            '/lob-assets.com/letters/ltr_4868c3b754655f90_thumb_small_1.png?exp'
            'ires=1540372221&signature=a5fRBJ22ZA78Vgpg34M9UfmHWTS3eha","medium'
            '":"https://lob-assets.com/letters/ltr_4868c3b754655f90_thumb_mediu'
            'm_1.png?expires=1540372221&signature=bAzL8sv935PY09FWSkpDpWKkyvGSW'
            'YF","large":"https://lob-assets.com/letters/ltr_4868c3b754655f90_t'
            'humb_large_1.png?expires=1540372221&signature=gsKvxXgrm4v4iZD3bOib'
            'K7jApNkEMdW"}],"expected_delivery_date":"2021-03-30","date_created'
            '":"2021-03-24T22:51:42.838Z","date_modified":"2021-03-24T22:51:42.'
            '838Z","send_date":"2021-03-24T22:51:42.838Z","use_type":"marketing'
            '","object":"postcard"}],"object":"list","previous_url":null,"next_'
            'url":null,"count":2}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Creates a new postcard given information
    def test_postcard_create(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"description":"demo","to":{"description":"Harry - Office","name":'
            '"Harry Zhang","company":"Lob","email":"harry@lob.com","phone":"555'
            '5555555","address_line1":"210 King St","address_line2":"# 6100","a'
            'ddress_city":"San Francisco","address_state":"CA","address_zip":"9'
            '4107","address_country":"US"},"from":{"description":"Harry - Offic'
            'e","name":"Harry Zhang","company":"Lob","email":"harry@lob.com","p'
            'hone":"5555555555","address_line1":"210 King St","address_line2":"'
            '# 6100","address_city":"San Francisco","address_state":"CA","addre'
            'ss_zip":"94107","address_country":"US"},"front":"tmpl_a1234dddg","'
            'back":"tmpl_a1234dddg","size":"6x9","mail_type":"usps_first_class"'
            ',"merge_variables":{"name":"Harry"},"metadata":{"spiffy":"true"},"'
            'send_date":"2017-11-01T00:00:00.000Z","use_type":"marketing","qr_c'
            'ode":{"position":"relative","redirect_url":"https://www.lob.com","'
            'width":"2.5","top":"2.5","right":"2.5","pages":"front,back"}}', PostcardEditable.from_dictionary)
        idempotency_key = '026e7634-24d7-486c-a0bb-4a17fd0eebc5'
        idempotency_key_2 = '026e7634-24d7-486c-a0bb-4a17fd0eebc5'

        # Perform the API call through the SDK function
        result = self.controller.postcard_create(body, idempotency_key, idempotency_key_2)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":"psc_208e45e48d271294","description":null,"metadata":{},"to"'
            ':{"id":"adr_210a8d4b0b76d77b","description":null,"name":null,"comp'
            'any":"LOB","phone":null,"email":null,"address_line1":"210 KING ST '
            'STE 6100","address_line2":null,"address_city":"SAN FRANCISCO","add'
            'ress_state":"CA","address_zip":"94107-1741","address_country":"UNI'
            'TED STATES","metadata":{},"date_created":"2018-12-08T03:01:07.651Z'
            '","date_modified":"2018-12-08T03:01:07.651Z","object":"address"},"'
            'url":"https://lob-assets.com/postcards/psc_208e45e48d271294.pdf?ve'
            'rsion=v1&expires=1619218302&signature=NfHHLBSr5tOHA_Z4kij4dKqZG8f3'
            'vMDtwvuFVeeF9pV_lylcjLsVVODhNCE5hR6-2slUr6t9WMNsi429Pj7_DA","carri'
            'er":"USPS","front_template_id":null,"back_template_id":null,"date_'
            'created":"2021-03-24T22:51:42.838Z","date_modified":"2021-03-24T22'
            ':51:42.838Z","send_date":"2021-03-24T22:51:42.838Z","use_type":"ma'
            'rketing","object":"postcard"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

