# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.sort_by import SortBy
from lob.models.billing_group_editable import BillingGroupEditable


class BillingGroupsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(BillingGroupsControllerTests, cls).setUpClass()
        cls.controller = cls.client.billing_groups
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your billing_groups. The billing_groups are returned sorted by creation date, with the most recently created billing_groups appearing first.
    def test_billing_groups_list(self):
        # Parameters for the API call
        limit = 10
        offset = 0
        include = None
        date_created = None
        date_modified = None
        sort_by = None

        # Perform the API call through the SDK function
        result = self.controller.billing_groups_list(limit, offset, include, date_created, date_modified, sort_by)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"data":[{"id":"bg_d5a5a89da9106f8","description":"Test billing_gr'
            'oup","metadata":{},"date_created":"2019-07-27T23:49:01.511Z","date'
            '_modified":"2019-07-27T23:49:01.511Z","object":"billing_group"},{"'
            'id":"bg_59b2150ae120887","description":"Test billing_group","metad'
            'ata":{},"date_created":"2019-03-29T10:22:34.642Z","date_modified":'
            '"2019-03-29T10:22:34.642Z","object":"billing_group"}],"object":"li'
            'st","next_url":null,"prev_url":null,"count":2}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

    # Creates a new billing_group with the provided properties.
    def test_billing_group_create(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"name":"Marketing Dept","description":"Usage group used for the M'
            'arketing Dept resource sends"}', BillingGroupEditable.from_dictionary)

        # Perform the API call through the SDK function
        result = self.controller.billing_group_create(body)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":"bg_c94e83ca2cd5121","name":"Marketing Dept","description":"'
            'Usage group used for the Marketing Dept resource sends","date_crea'
            'ted":"2017-11-07T22:56:10.962Z","date_modified":"2017-11-07T22:56:'
            '10.962Z","object":"billing_group"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

