# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper
from lob.models.beforeafter import Beforeafter
from lob.models.sort_by_1 import SortBy1


class ChecksControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(ChecksControllerTests, cls).setUpClass()
        cls.controller = cls.client.checks
        cls.response_catcher = cls.controller.http_call_back

    # Returns a list of your checks. The checks are returned sorted by creation date, with the most recently created checks appearing first.
    def test_checks_list(self):
        # Parameters for the API call
        limit = 10
        before_after = None
        include = None
        date_created = None
        metadata = None
        scheduled = None
        send_date = None
        mail_type = None
        sort_by = None

        # Perform the API call through the SDK function
        result = self.controller.checks_list(limit, before_after, include, date_created, metadata, scheduled, send_date, mail_type, sort_by)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)


