# -*- coding: utf-8 -*-

"""
lob

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

import json

from tests.controllers.controller_test_base import ControllerTestBase
from apimatic_core.utilities.comparison_helper import ComparisonHelper
from lob.api_helper import APIHelper


class IntlVerificationsControllerTests(ControllerTestBase):

    controller = None

    @classmethod
    def setUpClass(cls):
        super(IntlVerificationsControllerTests, cls).setUpClass()
        cls.controller = cls.client.intl_verifications
        cls.response_catcher = cls.controller.http_call_back

    # Verify an international (except US or US territories) address _with a live API key_. Requests to this endpoint with a test API key will return a dummy response based on the primary line you input.
    def test_intl_verification(self):
        # Parameters for the API call
        body = APIHelper.json_deserialize('{"recipient":"Harry Zhang","primary_line":"370 Water St","secondar'
            'y_line":"","city":"Summerside","state":"Prince Edward Island","pos'
            'tal code":"C1N 1C4","country":"CA"}')
        x_lang_output = None

        # Perform the API call through the SDK function
        result = self.controller.intl_verification(body, x_lang_output)

        # Test response code
        assert self.response_catcher.response.status_code == 200

        # Test headers
        expected_headers = {}
        expected_headers['ratelimit-limit'] = None
        expected_headers['ratelimit-remaining'] = None
        expected_headers['ratelimit-reset'] = None
        expected_headers['content-type'] = 'application/json'

        assert ComparisonHelper.match_headers(expected_headers, self.response_catcher.response.headers)

        
        # Test whether the captured response is as we expected
        assert result is not None
        expected_body = APIHelper.json_deserialize('{"id":"intl_ver_c7cb63d68f8d6","recipient":null,"primary_line":"37'
            '0 WATER ST","secondary_line":"","last_line":"SUMMERSIDE PE C1N 1C4'
            '","country":"CA","coverage":"SUBBUILDING","deliverability":"delive'
            'rable","status":"LV4","components":{"primary_number":"370","street'
            '_name":"WATER ST","city":"SUMMERSIDE","state":"PE","postal_code":"'
            'C1N 1C4"},"object":"intl_verification"}')
        received_body = APIHelper.json_deserialize(self.response_catcher.response.text)
        assert ComparisonHelper.match_body(expected_body, received_body)

